name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
    paths:
      - '!.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - '!.github/workflows/**'
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_c3233cc8-1557-4409-8e6d-75a29b9e0dd0
env:
  ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_CICD_TEST}}
  COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
jobs:
  deploy:
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Download Terragrunt
        run: >-
          wget
          https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.6/terragrunt_linux_amd64
          && mv terragrunt_linux_amd64 terragrunt && chmod u+x terragrunt && mv
          terragrunt /usr/local/bin/terragrunt
      - name: Terragrunt Version Check
        run: terragrunt version
