name: My Test Workflow (Skyu Generated)
'on':
  push:
    branches:
      - master
    paths:
      - '!.github/workflows/**'
  pull_request:
    branches:
      - master
    paths:
      - '!.github/workflows/**'
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_71418bef-4810-4d61-b7ac-192f2a302794
env:
  ENCODED_PIPELINE_SECRET: ${{secrets.TESTSERVICE2_CICD_TEST}}
  COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
  Hello: VALUEEEEEEE
jobs:
  deploy:
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Run :: Decoding Secrets'
        run: |2-

                if [ ! -x "$(command -v jq)" ]; then
                  echo "jq not found, installing..."
                  sudo apt-get update
                  sudo apt-get install -y jq
                fi
                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: Start
        run: |2-

              echo " Starting GitHub Action!" && 
              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
              
      - name: Step 1
        run: echo "Hello"
      - name: step2
        run: aaa
